### ISSUE TITLE
Beschreibe Design Pattern (3/3)

### ISSUE THREAD

**Issue by SaraBeki** [Lyasya-tech/VierGewinnt#3]
Wähle ein Design Pattern von https://refactoring.guru/design-patterns/catalog und beschreibe es.
Teile dem Team mit, welches Design Pattern du gewählt hast.

**Comment by DanielaHaumer** [comment]
Desing Pattern "Chain of Responsibility" beschrieben und ins File Entwurfsmuster.md hinzugefügt.
