### ISSUE TITLE
Konzept erstellen

### ISSUE THREAD

**Issue by DanielaHaumer** [Lyasya-tech/VierGewinnt#4]
Abklärung benötigte Klassen/Methoden.
Verantwortlichkeiten festlegen.

**Comment by DanielaHaumer** [comment]
Klassendiagramm erstellt und commited.

**Comment by Lyasya-tech** [comment]
Ordner docs angelegt, Klassendiagramm nach docs verschoben.

**Comment by SaraBeki** [comment]
Alle Änderungen siehe dokumentation.md.
